### ISSUE TITLE
进行复用优化后，APK无法安装

### ISSUE THREAD

**Issue by eirv** [L-JINBIN/ApkDataMultiplexing#3]
进行复用优化后，APK内文件压缩后大小都变成了0kb，导致APK无法被安装
![Screenshot_2023-04-17-14-08-59-847_bin mt plus](https://user-images.githubusercontent.com/64970244/232399422-08917fa1-82c8-44f6-8c0b-1cba6dc10e1d.jpg)
![Screenshot_2023-04-17-14-09-03-210_bin mt plus](https://user-images.githubusercontent.com/64970244/232399423-1e299ea9-e9fd-4e4e-9ebb-ae08a59b2b21.jpg)
安装报错：
```
Failure [INSTALL_FAILED_INVALID_APK: INSTALL_FAILED_INVALID_APK: Failed to extract native libraries, res=-2]
```

**Comment by eirv** [comment]
> 可否提供下APK文件？

https://wwyy.lanzouy.com/iRCwD0szdzre
密码:ebb1

**Comment by L-JINBIN** [comment]
MT中针对复用优化的文件，显示的压缩后大小都是0B，这个是故意的，不然全选所有文件后统计出来的压缩后文件大小会大于zip的文件大小。
我使用MT的加强去签测试后，复用优化并没有导致apk无法安装，不知道你那边无法安装是文件问题还是系统问题，你的系统是安卓几？方便的话把你那边无法安装的apk文件也发一下。

**Comment by eirv** [comment]
> MT中针对复用优化的文件，显示的压缩后大小都是0B，这个是故意的，不然全选所有文件后统计出来的压缩后文件大小会大于zip的文件大小。
> 我使用MT的加强去签测试后，复用优化并没有导致apk无法安装，不知道你那边无法安装是文件问题还是系统问题，你的系统是安卓几？方便的话把你那边无法安装的apk文件也发一下。

我这里是安卓13
https://github.com/eirv/test/releases/download/a/a.zip

**Comment by eirv** [comment]
> MT中针对复用优化的文件，显示的压缩后大小都是0B，这个是故意的，不然全选所有文件后统计出来的压缩后文件大小会大于zip的文件大小。
> 我使用MT的加强去签测试后，复用优化并没有导致apk无法安装，不知道你那边无法安装是文件问题还是系统问题，你的系统是安卓几？方便的话把你那边无法安装的apk文件也发一下。

感谢您从百忙中抽出时间，原包我是用zip4j加入到apk中的，这个问题应该和zip4j有关，我刚用mt重新处理了一下，安装成功了
